"""add blacklist table

Revision ID: 175af8dfbbbd
Revises: ec2115061c2c
Create Date: 2022-01-13 13:18:57.094259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175af8dfbbbd'
down_revision = 'ec2115061c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
